TIMESTAMP: 2026-05-18
dependabot:
    exists: true
    has_ecosystem:
        github-actions: true
        npm: false
        pip: false
dependabot_alerts: {}
dependencies:
    count: 0
    github:
        count: 0
        list: ''
    js:
        count: 0
        list: ''
    js.all:
        count: 0
        list: ''
    js.dev:
        count: 0
        list: ''
    pypi:
        count: 0
        list: ''
    pypi_all:
        count: 0
        list: ''
django_packages:
    django_42:
        count: 0
        list: '[]'
    total:
        count: 0
        list: '[]'
    upgraded:
        count: 0
        list: '[]'
docs:
    build_badge: false
    python_version: null
exists:
    .coveragerc: false
    .editorconfig: true
    .gitignore: true
    .pii_annotations.yml: false
    .travis.yml: false
    CHANGELOG.rst: false
    Makefile: false
    README: true
    commitlint.yml: true
    dependabot.yml: true
    openedx.yaml: true
    package.json: false
    pylintrc: false
    requirements: false
    setup.cfg: false
    setup.py: false
    tox.ini: false
    transifex_config: false
github:
    allows_merge_commit: true
    allows_rebase_merge: true
    allows_squash_merge: true
    branch_count: 8
    build_details: '{"total_duration": "331 minutes 43 seconds", "checks": [{"name":
        "bulk_update (openedx-platform)", "duration": "2 minutes 48 seconds"}, {"name":
        "bulk_update (edx-search)", "duration": "1 minutes 14 seconds"}, {"name":
        "bulk_update (edx-bulk-grades)", "duration": "1 minutes 12 seconds"}, {"name":
        "bulk_update (staff-graded-xblock)", "duration": "1 minutes 11 seconds"},
        {"name": "bulk_update (frontend-component-footer)", "duration": "1 minutes
        11 seconds"}, {"name": "bulk_update (edx-when)", "duration": "1 minutes 11
        seconds"}, {"name": "bulk_update (django-wiki)", "duration": "1 minutes 11
        seconds"}, {"name": "bulk_update (frontend-app-admin-portal)", "duration":
        "1 minutes 11 seconds"}, {"name": "bulk_update (edx-organizations)", "duration":
        "1 minutes 10 seconds"}, {"name": "bulk_update (edx-proctoring)", "duration":
        "1 minutes 10 seconds"}, {"name": "bulk_update (edx-bulk-grades)", "duration":
        "1 minutes 10 seconds"}, {"name": "bulk_update (platform-plugin-aspects)",
        "duration": "1 minutes 10 seconds"}, {"name": "bulk_update (edx-celeryutils)",
        "duration": "1 minutes 9 seconds"}, {"name": "bulk_update (edx-notes-api)",
        "duration": "1 minutes 9 seconds"}, {"name": "bulk_update (edx-val)", "duration":
        "1 minutes 9 seconds"}, {"name": "bulk_update (django-pyfs)", "duration":
        "1 minutes 8 seconds"}, {"name": "bulk_update (openedx-ledger)", "duration":
        "1 minutes 8 seconds"}, {"name": "bulk_update (brand-openedx)", "duration":
        "1 minutes 8 seconds"}, {"name": "bulk_update (xblock-drag-and-drop-v2)",
        "duration": "1 minutes 7 seconds"}, {"name": "bulk_update (RecommenderXBlock)",
        "duration": "1 minutes 7 seconds"}, {"name": "bulk_update (xblocks-core)",
        "duration": "1 minutes 7 seconds"}, {"name": "bulk_update (codejail)", "duration":
        "1 minutes 7 seconds"}, {"name": "bulk_update (frontend-app-learner-dashboard)",
        "duration": "1 minutes 7 seconds"}, {"name": "bulk_update (openedx-calc)",
        "duration": "1 minutes 7 seconds"}, {"name": "bulk_update (cypress-e2e-tests)",
        "duration": "1 minutes 7 seconds"}, {"name": "bulk_update (acid-block)", "duration":
        "1 minutes 6 seconds"}, {"name": "bulk_update (edx-when)", "duration": "1
        minutes 6 seconds"}, {"name": "bulk_update (cc2olx)", "duration": "1 minutes
        6 seconds"}, {"name": "bulk_update (i18n-tools)", "duration": "1 minutes 6
        seconds"}, {"name": "bulk_update (xblock-free-text-response)", "duration":
        "1 minutes 5 seconds"}, {"name": "bulk_update (xqueue)", "duration": "1 minutes
        5 seconds"}, {"name": "bulk_update (edx-enterprise-subsidy-client)", "duration":
        "1 minutes 5 seconds"}, {"name": "bulk_update (frontend-app-account)", "duration":
        "1 minutes 5 seconds"}, {"name": "bulk_update (frontend-app-learner-record)",
        "duration": "1 minutes 5 seconds"}, {"name": "bulk_update (edx-lint)", "duration":
        "1 minutes 4 seconds"}, {"name": "bulk_update (api-doc-tools)", "duration":
        "1 minutes 4 seconds"}, {"name": "bulk_update (pytest-repo-health)", "duration":
        "1 minutes 4 seconds"}, {"name": "bulk_update (frontend-app-admin-console)",
        "duration": "1 minutes 3 seconds"}, {"name": "bulk_update (frontend-enterprise)",
        "duration": "1 minutes 3 seconds"}, {"name": "bulk_update (frontend-component-header)",
        "duration": "1 minutes 3 seconds"}, {"name": "bulk_update (credentials-themes)",
        "duration": "1 minutes 3 seconds"}, {"name": "bulk_update (codejail-service)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (help-tokens)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (taxonomy-connector)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (frontend-app-discussions)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (frontend-app-authn)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (frontend-app-learning)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (openedx-proposals)",
        "duration": "1 minutes 2 seconds"}, {"name": "bulk_update (crowdsourcehinter)",
        "duration": "1 minutes 1 seconds"}, {"name": "bulk_update (django-user-tasks)",
        "duration": "1 minutes 1 seconds"}, {"name": "bulk_update (edx-rest-api-client)",
        "duration": "1 minutes 1 seconds"}, {"name": "bulk_update (enterprise-integrated-channels)",
        "duration": "1 minutes 1 seconds"}, {"name": "bulk_update (frontend-app-communications)",
        "duration": "1 minutes 1 seconds"}, {"name": "bulk_update (frontend-app-profile)",
        "duration": "1 minutes 1 seconds"}, {"name": "bulk_update (edx-rbac)", "duration":
        "1 minutes 1 seconds"}, {"name": "bulk_update (ccx-keys)", "duration": "1
        minutes 0 seconds"}, {"name": "bulk_update (edx-django-sites-extensions)",
        "duration": "1 minutes 0 seconds"}, {"name": "bulk_update (edx-enterprise-data)",
        "duration": "1 minutes 0 seconds"}, {"name": "bulk_update (django-config-models)",
        "duration": "0 minutes 59 seconds"}, {"name": "bulk_update (super-csv)", "duration":
        "0 minutes 59 seconds"}, {"name": "bulk_update (xblock-image-explorer)", "duration":
        "0 minutes 59 seconds"}, {"name": "bulk_update (xblock-in-video-quiz)", "duration":
        "0 minutes 59 seconds"}, {"name": "bulk_update (xblock-sdk)", "duration":
        "0 minutes 58 seconds"}, {"name": "bulk_update (edx-cookiecutters)", "duration":
        "0 minutes 58 seconds"}, {"name": "bulk_update (frontend-app-ora)", "duration":
        "0 minutes 56 seconds"}, {"name": "bulk_update (frontend-base)", "duration":
        "0 minutes 54 seconds"}, {"name": "bulk_update (aspects-dbt)", "duration":
        "0 minutes 52 seconds"}, {"name": "bulk_update (platform-roadmap)", "duration":
        "0 minutes 52 seconds"}, {"name": "bulk_update (forum)", "duration": "0 minutes
        49 seconds"}, {"name": "bulk_update (axim-engineering)", "duration": "0 minutes
        47 seconds"}, {"name": "bulk_update (openedx-k8s-harmony)", "duration": "0
        minutes 47 seconds"}, {"name": "bulk_update (openedx-backstage)", "duration":
        "0 minutes 46 seconds"}, {"name": "bulk_update (wg-governance)", "duration":
        "0 minutes 46 seconds"}, {"name": "repos_list", "duration": "0 minutes 5 seconds"},
        {"name": "repos_list", "duration": "0 minutes 4 seconds"}, {"name": "repos_list",
        "duration": "0 minutes 4 seconds"}, {"name": "repos_list", "duration": "0
        minutes 3 seconds"}, {"name": "repos_list", "duration": "0 minutes 3 seconds"},
        {"name": "repos_list", "duration": "0 minutes 3 seconds"}, {"name": "repos_list",
        "duration": "0 minutes 3 seconds"}, {"name": "repos_list", "duration": "0
        minutes 2 seconds"}, {"name": "repos_list", "duration": "0 minutes 2 seconds"}]}'
    code_of_conduct: Other
    created_at: 2022-01-05 17:05:00
    default_branch: master
    description: Centralized openedx repository workflows, community health files,
        etc.
    disk_usage_kb: 370
    fork_count: 33
    has_issues: true
    has_wiki: false
    is_archived: false
    is_disabled: false
    is_fork: false
    is_locked: false
    is_private: false
    last_push: 2026-05-14 19:35:38
    license: Apache License 2.0
    pulls_count: 0
github_actions: false
language_bytes:
    css: 0
    dockerfile: 0
    html: 0
    javascript: 0
    makefile: 0
    python: 2193
    shell: 0
makefile:
    pip-installed: false
    quality: false
    quality-js: false
    quality-python: false
    test: false
    test-js: false
    test-python: false
    upgrade: false
npm_package: ''
org_name: openedx
pinned_python_dependencies: 0
readme:
    bad_links: []
    getting-help: false
    good_links:
    - https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
    irc-missing: true
    mailing-list-missing: true
    security: false
readthedocs_config:
    exists: false
    file_name: ''
    version: ''
renovate:
    configured: false
    last_pr: null
    oldest_open_pr_date: null
    total_open_prs: null
requires:
    boto: false
    django: false
    nose: false
    pytest: false
setup_py:
    py38_classifiers: false
    python_versions: []
tox_ini:
    has_section:
        testenv: false
        testenv:quality: false
        tox: false
    uses_whitelist_externals: false
travis_ci:
    active: false
    active_on_com: false
    active_on_org: false
travis_yml:
    parsable: false
    py38_tests: false
    python_versions: []
ubuntu_packages:
    apt_get_packages: []
    docker_packages: null
    yml_files: '[]'
