TIMESTAMP: 2026-04-23
dependabot:
    exists: false
    has_ecosystem:
        github-actions: false
        npm: false
        pip: false
dependabot_alerts: {}
dependencies:
    count: 1
    github:
        count: 0
        list: ''
    js:
        count: 0
        list: '{}'
    js.all:
        count: 0
        list: '{}'
    js.dev:
        count: 1
        list: '{"browserslist": "4.24.2"}'
    pypi:
        count: 0
        list: ''
    pypi_all:
        count: 0
        list: ''
django_packages:
    django_42:
        count: 0
        list: '[]'
    total:
        count: 0
        list: '[]'
    upgraded:
        count: 0
        list: '[]'
docs:
    build_badge: false
    python_version: null
exists:
    .coveragerc: false
    .editorconfig: false
    .gitignore: true
    .pii_annotations.yml: false
    .travis.yml: false
    CHANGELOG.rst: false
    Makefile: false
    README: true
    commitlint.yml: true
    dependabot.yml: false
    openedx.yaml: false
    package.json: true
    pylintrc: false
    requirements: false
    setup.cfg: false
    setup.py: false
    tox.ini: false
    transifex_config: false
github:
    allows_merge_commit: false
    allows_rebase_merge: false
    allows_squash_merge: true
    branch_count: 1
    build_details: '{"total_duration": "0 minutes 41 seconds", "checks": [{"name":
        "Release", "duration": "0 minutes 41 seconds"}]}'
    code_of_conduct: Other
    created_at: 2021-11-02 20:06:24
    default_branch: master
    description: ''
    disk_usage_kb: 40
    fork_count: 5
    has_issues: true
    has_wiki: false
    is_archived: false
    is_disabled: false
    is_fork: false
    is_locked: false
    is_private: false
    last_push: 2026-01-27 15:38:03
    license: GNU AGPLv3
    pulls_count: 0
github_actions: false
language_bytes:
    css: 0
    dockerfile: 0
    html: 0
    javascript: 341
    makefile: 0
    python: 0
    shell: 0
makefile:
    pip-installed: false
    quality: false
    quality-js: false
    quality-python: false
    test: false
    test-js: false
    test-python: false
    upgrade: false
npm_package: '@edx/browserslist-config'
org_name: openedx
pinned_python_dependencies: 0
readme:
    bad_links:
    - 'https://www.npmjs.com/package/@edx/browserslist-config: 403'
    getting-help: false
    good_links:
    - https://img.shields.io/npm/l/@edx/browserslist-config
    - https://img.shields.io/npm/v/@edx/browserslist-config
    - https://github.com/browserslist/browserslist
    - https://support.edx.org/hc/en-us/articles/206211848-What-are-the-system-requirements-and-supported-browsers-on-edX
    irc-missing: true
    mailing-list-missing: true
    security: false
readthedocs_config:
    exists: false
    file_name: ''
    version: ''
renovate:
    configured: true
    last_pr: null
    oldest_open_pr_date: null
    total_open_prs: 0
requires:
    boto: false
    django: false
    nose: false
    pytest: false
setup_py:
    py38_classifiers: false
    python_versions: []
tox_ini:
    has_section:
        testenv: false
        testenv:quality: false
        tox: false
    uses_whitelist_externals: false
travis_ci:
    active: false
    active_on_com: false
    active_on_org: false
travis_yml:
    parsable: false
    py38_tests: false
    python_versions: []
ubuntu_packages:
    apt_get_packages: []
    docker_packages: null
    yml_files: '[]'
